<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>vdf</string>
	</array>
	<key>name</key>
	<string>View Filter File</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>(?i)^\s*include\s*&lt;[/äöüa-z\-_.\\0-9]+&gt;</string>
			<key>name</key>
			<string>keyword.viewFilter</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#.*</string>
			<key>name</key>
			<string>comment.line.number-sign.viewFilter</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[\+\-0-9.]+</string>
			<key>name</key>
			<string>constant.numeric.viewFilter</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\boff\b</string>
			<key>name</key>
			<string>constant.numeric.viewFilter</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)'[a-z0-9\-_/äöü.:=\+. ]+'</string>
			<key>name</key>
			<string>string.quoted.single.viewFilter</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?=B)</string>
			<key>name</key>
			<string>element.viewFilter</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>part.viewFilter</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)^\s*(BEAM|CEILING|COLUMN|COMPONENT|DIM|DTM|ELEMENT|FILE|FLOOR|GLOBAL|GRID|LABEL|PERFORATOR|REFPLANE|ROOF|ROOF_CON|SECTION|SLAB|SOLID|SPACE|STAIR|WALL|UNITS)\s+([a-zA-Z_0-9]*\b)</string>
			<key>name</key>
			<string>element.viewFilter</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.viewFilter</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.viewFilter</string>
				</dict>
			</dict>
			<key>name</key>
			<string>attribute.viewFilter</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)[a-z_öäü]*</string>
					<key>name</key>
					<string>attribute.name.viewFilter</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(i|r|u|t)\b</string>
					<key>name</key>
					<string>attribute.type.viewFilter</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)'[a-z0-9_/äöü ]+'</string>
					<key>name</key>
					<string>attribute.value.viewFilter</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b[0-9]+\b</string>
					<key>name</key>
					<string>attribute.value.viewFilter</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\[|\{)</string>
					<key>end</key>
					<string>(\]|\})</string>
					<key>name</key>
					<string>attribute.value.viewFilter</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(i|r|u|t)\b</string>
			<key>name</key>
			<string>attribute.type.viewFilter</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(drw|sym|xha|txt|mat)\b</string>
			<key>name</key>
			<string>displayoption.viewFilter</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(ifdef|else|endif)\b</string>
			<key>name</key>
			<string>keyword.viewFilter</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.viewFilter.speedikon</string>
	<key>uuid</key>
	<string>2c2d866d-8c11-4b62-b5e2-5c2ba0966313</string>
</dict>
</plist>
